export enum BlockType {
  PARAGRAPH = 'paragraph',
  HEADING_1 = 'heading_1',
  HEADING_2 = 'heading_2',
  HEADING_3 = 'heading_3',
  BULLET_LIST = 'bullet_list',
  NUMBERED_LIST = 'numbered_list',
  CHECKLIST = 'checklist',
  TABLE = 'table',
  IMAGE = 'image',
  FILE = 'file',
  LINK_BOOKMARK = 'link_bookmark',
  LINK_EMBED = 'link_embed',
  CODE = 'code',
  DIVIDER = 'divider',
  CALLOUT = 'callout',
  QUOTE = 'quote',
}
