version: "3.8"

# Переопределения для локальной разработки
services:
  backend:
    environment:
      - NODE_ENV=development
      - DB_SYNCHRONIZE=true
    volumes:
      # Для hot reload в разработке (опционально)
      # - ./apps/backend/src:/app/apps/backend/src
      - backend_node_modules:/app/apps/backend/node_modules

  frontend:
    # Для разработки можно добавить volume для hot reload
    volumes:
      - frontend_dist:/usr/share/nginx/html

  postgres:
    # Дополнительные настройки для разработки
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    # Можно добавить порт для прямого доступа
    ports:
      - "5432:5432"

volumes:
  backend_node_modules:
  frontend_dist: 