version: "3.8"

# Переопределения для локальной разработки
services:
  backend:
    environment:
      - NODE_ENV=development
      - DB_SYNCHRONIZE=true

  frontend:
    # Для разработки без дополнительных volumes
    restart: unless-stopped

  postgres:
    # Дополнительные настройки для разработки
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"

# Убираем volumes, которые не используются
# volumes:
#   backend_node_modules:
#   frontend_dist: 