version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: timetracker_postgres_dev
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: GvXWmzMLP03HNmrp
      POSTGRES_DB: nestdb
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yourusername"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: timetracker_adminer_dev
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres_dev_data: 