export { default as LoginPage } from "./auth/login.page";
export { default as RegisterPage } from "./auth/register.page";
export { default as PlansPage } from "./plans/plans.page";
export { default as ProjectsPage } from "./project/projects.page";
export { default as ProjectDetailPage } from "./project/project-detail.page";
export { default as SettingsPage } from "./settings/settings.page";
export { default as TaskDetailPage } from "./tasks/task-detail.page";
export { default as UserPage } from "./user/user.page";
export { DocumentPage } from "./document-page/DocumentPage";
export { DocumentsListPage } from "./documents-list-page/DocumentsListPage"; 