export enum NOTIFICATION_TYPE {
  FRIENDSHIP_INVITATION = "friendship_invitation",
  FRIENDSHIP_INVITATION_ACCEPTED = "friendship_invitation_accepted",
  FRIENDSHIP_INVITATION_DECLINED = "friendship_invitation_declined",
  PROJECT_LEAVE_FOR_USER = "project_leave_for_user",
  PROJECT_LEAVE_FOR_OWNER = "project_leave_for_owner",
  PROJECT_INVITATION_ACCEPTED = "project_invitation_accepted",
  PROJECT_INVITATION_DECLINED = "project_invitation_declined",
  PROJECT_INVITATION = "project_invitation",
  PROJECT_DELETE = "project_delete",
  PROJECT_COMMENT = "project_comment",
  TASK_INVITATION_ACCEPTED = "task_invitation_accepted",
  TASK_INVITATION_DECLINED = "task_invitation_declined",
  TASK_INVITATION = "task_invitation",
  TASK_COMMENT = "task_comment",
  TIME_LOG_START = "time_log_start",
  TIME_LOG_STOP = "time_log_stop",
}
