name: TT

on:
  push:
    branches: [main]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Frontend Build
        run: |
          docker build -f apps/frontend/Dockerfile -t frontend-verify .

      - name: Verify Backend Build
        run: |
          docker build -f apps/backend/Dockerfile -t backend-verify .

  deploy:
    needs: verify-build  # Будет выполняться ТОЛЬКО если verify-build успешен
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Safe Deploy
        run: |
          cd /home/deploy/projects/TimeTracker
          git pull origin main
          
          # Создаем backup текущей версии
          docker tag timetracker_backend:latest timetracker_backend:backup-$(date +%Y%m%d%H%M%S) || true
          
          # Пытаемся развернуть новую версию
          if ! docker-compose up -d --build; then
            echo "❌ Deployment failed! Rolling back..."
            docker-compose down
            docker-compose up -d
            exit 1
          fi
