name: TT

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read  # Добавляем минимальные permissions
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker
        run: |
          docker compose down
          docker compose up -d
