name: TimeTracker CI/CD

on:
  push:
    branches: [main]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Verify frontend build
        run: |
          docker build \
            -f ./apps/frontend/Dockerfile \
            --target frontend-builder \
            -t timetracker-frontend-verify \
            ./apps/frontend

      - name: Verify backend build
        run: |
          docker build \
            -f ./apps/backend/Dockerfile \
            --target backend-builder \
            -t timetracker-backend-verify \
            ./apps/backend

  deploy:
    needs: verify-build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update and deploy
        run: |
          cd /home/deploy/projects/TimeTracker
          git pull origin main
          
          # Build new images first
          docker-compose build || exit 1
          
          # Stop and remove old containers
          docker-compose down || true
          
          # Start new containers
          docker-compose up -d