name: TT

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update and restart containers
        run: |
          cd /home/deploy/projects/TimeTracker
          git pull origin main
          docker compose down
          docker compose up -d