name: TT

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Используем self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub (если нужно)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and deploy
        run: |
          cd /home/deploy/projects/TimeTracker
          git pull origin main
          docker compose down
          docker compose up -d --build