name: TT

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Шаг 1: Получение кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Остановка старых контейнеров и запуск новых
      - name: Update and restart containers
        run: |
          cd /home/deploy/projects/TimeTracker
          git pull origin main
          docker compose down --remove-orphans  # Остановка и удаление контейнеров
          docker compose up -d  # Запуск контейнеров без пересборки